Added Issue Templates `bug`, `feature`
ValkyrienSkies/Eureka pull request #106
Opened 2023-01-18 09:29 UTC by PSGitHubUser1

#103 

Done.. [Did the changes as said]

2023-01-18 13:51 UTC, copperwarrior commented
In the future, please keep your changes on the same pull request so they can be reviewed and closed properly.

2023-01-18 13:54 UTC, PSGitHubUser1 commented
I did this as I don't know how to update/edit a PR

2023-01-18 14:04 UTC, copperwarrior requested changes
Much closer but still needs some changes that were mentioned in the earlier PR.

2023-01-18 14:04 UTC, copperwarrior commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +     - 1.17.x
1.17.x is not supported. The previous review stated that an option of "Other" should be available, in case newer versions are updated and the template is not.

The end result should look like:
- 1.18.x
- 1.16.x
- Other

2023-01-18 14:04 UTC, copperwarrior commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +     - label: "I am sure that my issue is releted to <a href='https://www.curseforge.com/minecraft/mc-mods/eureka-ships' target='_blank'>Eureka</a>, not <a href='https://github.com/ValkyrienSkies/Val
Wording: Related*

2023-01-18 14:04 UTC, copperwarrior commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +       required: true
This checkbox should be optional.

2023-01-18 14:04 UTC, copperwarrior commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +description: Please specify that it is a bug report
In my previous review, I said to specify that it is a bug report. I should have been more specific, my apologies.
The wording should be: "Create a bug report to help us improve (search for duplicates first)"

2023-01-18 14:04 UTC, copperwarrior commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +     - Linux (Specify the name)
This tells the user to specify the name of their operating system, but does not provide a means to do so. Please change this from a dropdown to a text box where a user can write in their operating system.

2023-01-18 14:04 UTC, copperwarrior commented on .github/ISSUE_TEMPLATE/config.yml
> +blank_issues_enabled: true
In my previous review I asked for this to be optional, in order to allow people with small and quick issues to have an alternative to the two templates.

2023-01-18 14:04 UTC, copperwarrior commented on .github/ISSUE_TEMPLATE/feature_request.yml
> +     - label: "I have checked that this feature <a href='https://github.com/ValkyrienSkies/Eureka/issues' target='_blank'>is not already asked.</a>"
Wording: "Requested" instead of "Asked"

2023-01-18 14:04 UTC, copperwarrior commented on .github/ISSUE_TEMPLATE/feature_request.yml
> + - type: checkboxes
Please provide a version dropdown with the options 1.16.x, 1.18.x, and Other

The end result should look like:
- 1.18.x
- 1.16.x
- Other

2023-01-18 14:05 UTC, copperwarrior commented
Updating your fork will automatically update the pull request.

2023-06-14 21:12 UTC, Rubydesic commented
made a slightly different issue template, but thank you for the idea and template to work off of.

2023-06-14 21:12 UTC, closed without merging