ComputerCraft Integration for Eureka Ship Helm
ValkyrienSkies/Eureka pull request #62
Opened 2022-12-14 15:18 UTC by TechTastic

Turns ShipHelmBlock into a CC Peripheral

Added ShipHelmPeripheral and ShipHelmPeripheralProvider
Minor change to EurekaModFabric and EurekaModForge to test for if ComputerCraft is loaded and/or disabled via configs
Added Config Option to disable ComputerCraft integration
Added CC Tweaked and CC Restitched to build.gradle for Forge and Fabric respectively using Curse Maven and modCompileOnly

2022-12-14 15:41 UTC, copperwarrior commented
canDisassemble, isDisassembling, and isAligning should not be revealed to the client because they operate in ways that a client may find confusing.

2022-12-14 15:46 UTC, TechTastic commented
> canDisassemble, isDisassembling, and isAligning should not be revealed to the client because they operate in ways that a client may find confusing.

I both agree and disagree

They might find it confusing but it can also be a great boon for intricate ship control programs

Such as that you dont move when you are aligning, so the smart developer knowing that can use isAligning() to check before attempting any movement and can take appropriate action or a person may want to be able to disassemble() but may want to simply check if they even can, thus theyll use canDisassemble() and depoending on the outcome, take appropriate action

2022-12-14 16:06 UTC, copperwarrior commented
The smart developer can also keep track of when they start and stop aligning, and detect if a ship is able to disassemble at all by using the angles.
If you intend to keep these methods, they need to work in a manner consistent with what the client would expect.

2022-12-14 17:25 UTC, ewoudje commented
I have to agree with copper, although i think canDissassemble is fine, but i think its better to hide the isAligning and isDissambling mainly cus these could be replaced at any time. (disassembly is still not a working thing so). Maybe also expose a getRotation

2022-12-14 17:44 UTC, ewoudje requested changes

2022-12-14 17:44 UTC, ewoudje commented on fabric/src/main/java/org/valkyrienskies/eureka/fabric/integrations/cc_restitched/ShipHelmPeripheral.java
> +    BlockPos pos;
Make these fields private since they're not used outside the class itself.

2022-12-14 17:44 UTC, ewoudje commented on fabric/src/main/java/org/valkyrienskies/eureka/fabric/integrations/cc_restitched/ShipHelmPeripheral.java
> +                        fakePlayer = new SeatedControllingPlayer(world.getBlockState(pos).getValue(BlockStateProperties.HORIZONTAL_FACING).getOpposite());
Is this pos you are using the helm position or the computer position? I would like it to use the orientation of the helm for this.

2022-12-14 17:44 UTC, ewoudje commented on fabric/src/main/java/org/valkyrienskies/eureka/fabric/integrations/cc_restitched/ShipHelmPeripheral.java
> +    public boolean applyThrust(String direction) throws LuaException {
Can you add some comments here and there cus this is a very big method wich is fine, but its easier for later maintaining that there are some comments.

2022-12-14 17:44 UTC, ewoudje commented on fabric/src/main/java/org/valkyrienskies/eureka/fabric/integrations/cc_restitched/ShipHelmPeripheral.java
> +        if (!world.isClientSide()) {
So im unsure if you need world.isClientSide everywhere? is this not only called server-side. Also i recommend nesting everything less, so more in the style of `if (world.isClientSide()) return 0;` and then more code behind it without any nesting. This is easier to read.

2022-12-14 17:44 UTC, ewoudje commented on fabric/src/main/java/org/valkyrienskies/eureka/fabric/integrations/cc_restitched/ShipHelmPeripheral.java
> +        if (!world.isClientSide()) {
(this is ofc not a requirement for merging but just a tip)

2022-12-14 17:47 UTC, TechTastic commented on fabric/src/main/java/org/valkyrienskies/eureka/fabric/integrations/cc_restitched/ShipHelmPeripheral.java
> +                        fakePlayer = new SeatedControllingPlayer(world.getBlockState(pos).getValue(BlockStateProperties.HORIZONTAL_FACING).getOpposite());
the Helm as the position is passed from the PeripheralProvider which gives the Peripheral's position (which is the Ship Helm)

2022-12-14 17:48 UTC, TechTastic commented on fabric/src/main/java/org/valkyrienskies/eureka/fabric/integrations/cc_restitched/ShipHelmPeripheral.java
> +        if (!world.isClientSide()) {
fair, i wasnt thinking in that vein, ill try it

2022-12-14 17:49 UTC, TechTastic commented on fabric/src/main/java/org/valkyrienskies/eureka/fabric/integrations/cc_restitched/ShipHelmPeripheral.java
> +    public boolean applyThrust(String direction) throws LuaException {
sure, its basically me forcing the impulse for whatever direction to stay at 1.0f for 20 game ticks (~1 second)

2022-12-14 17:49 UTC, TechTastic commented on fabric/src/main/java/org/valkyrienskies/eureka/fabric/integrations/cc_restitched/ShipHelmPeripheral.java
> +    BlockPos pos;
alright

2022-12-14 21:53 UTC, TechTastic commented
Ok, so Fabric is fully working and tested but Forge can not be tested in development due to CC: Tweaked either not remapping despite modCompileOnly or refusing to load and I can not outside of the IDE due to CentOS and Forge disagreeing on where .minecraft is and whether there is a launcher_profiles.json

2022-12-15 03:03 UTC, TechTastic commented
This is now fully working

Game does not crash nor error out due to missing classes if CCT/CCR are not found and Forge matches Fabric


Both Modloader Builds have been tested outside the dev environment via CurseForge

2022-12-16 21:45 UTC, ewoudje approved these changes
Looking good

2022-12-16 21:49 UTC, merged