[1.18.2] ComputerCraft Integration
ValkyrienSkies/Eureka pull request #74
Opened 2022-12-20 03:41 UTC by TechTastic

Turns ShipHelmBlock into a CC Peripheral

Added ShipHelmPeripheral and ShipHelmPeripheralProvider
Minor change to EurekaModFabric and EurekaModForge to test for if ComputerCraft is loaded and/or disabled via configs
Added Config Option to disable ComputerCraft integration
Added CC Tweaked and CC Restitched to build.gradle for Forge and Fabric respectively using Curse Maven and modCompileOnly

ShipHelmPeripheral provides multiple methods to manipulate ad read information to/from Eureka ships
 - forward() 
   - changes forwardImpulse (1.0f) in the SeatedControllingPlayer attachment and holds it for a second
 - reverse()
    - changes forwardImpulse (-1.0f) in the SeatedControllingPlayer attachment and holds it for a second
 - turnLeft()
    - changes leftImpulse (1.0f) in the SeatedControllingPlayer attachment and holds it for a second
 - turnRight()
    - changes leftImpulse (-1.0f) in the SeatedControllingPlayer attachment and holds it for a second
 - raise()
    - changes upImpulse (1.0f) in the SeatedControllingPlayer attachment and holds it for a second
 - lower()
    - changes upImpulse (-1.0f) in the SeatedControllingPlayer attachment and holds it for a second
 - isCruising()
    - grabs the boolean in SeatedControllingPlayer
 - startCruising()
   - changes the boolean in SeatedControllingPlayer
 - stopCruising()
   - changes the boolean in SeatedControllingPlayer
 - startAlignment()
   - changes the boolean in SeatedControllingPlayer
 - stopAlignment()
   - changes the boolean in SeatedControllingPlayer
 - disassemble()
   - calls to the disassemble() method in the ShipHelmBlockEntity
 - assemble()
   - calls to the disassemble() method in the ShipHelmBlockEntity
 - getBalloonAmount()
   - grabs the int from EurekaShipControl
 - getAnchorAmount()
   - grabs the int from EurekaShipControl
 - getActiveAnchorAmount()
   - grabs the int from EurekaShipControl
 - areAnchorsActive()
   - grabs the int from EurekaShipControl
 - getShipHelmAmount()

2022-12-20 10:40 UTC, ewoudje requested changes
Looks good, same thing with if nesting; but doesn't realy matter. But the most important part is removing the double code.

2022-12-20 10:40 UTC, ewoudje commented on fabric/src/main/java/org/valkyrienskies/eureka/fabric/integration/cc_restitched/ShipHelmPeripheral.java
> +                ship.saveAttachment(SeatedControllingPlayer.class, fakePlayer);
Pretty sure you don't need to save it afterwards

2022-12-20 10:40 UTC, ewoudje commented on forge/src/main/java/org/valkyrienskies/eureka/forge/integration/cc_tweaked/ShipHelmPeripheral.java
> +public class ShipHelmPeripheral implements IPeripheral {
Remove this double code. There is prob a reason you did this but figure out a way to not dupe the code.

2022-12-27 06:47 UTC, closed without merging

2024-02-25 19:20 UTC, flashgnash commented
Has this PR been given up on?

2024-02-28 20:42 UTC, ewoudje commented
I think this was added in CC:VS mod